server:
  port: 7002
  ssl:
    key-store-type: PKCS12
    key-store: classpath:config/common/cert/local-config-server.p12
    key-store-password: d?ba5#?&WA#dSy}LQ(51
    protocol: TLS
    enabled-protocols: TLSv1.3,TLSv1.2
    ciphers: TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,DHE-RSA-AES256-GCM-SHA384,DHE-RSA-AES128-GCM-SHA256,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-AES128-GCM-SHA256
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/craigmiller160/local-config-server-store.git
          username: craigmiller160@gmail.com
          password: ${GIT_HUB_PASSWORD}
          search-paths:
            - '*'
        security:
          username: user
          password: '{bcrypt}$2a$10$lz.0VwmpdubNVy4quE57FOk3FYTcB6GGSyKCA9RG0Xaj00ojJ5QXW'