apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-config-server
  labels:
    app: local-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-config-server
  template:
    metadata:
      labels:
        app: local-config-server
    spec:
      containers:
        - name: local-config-server
          image: local-config-server:1.2.0-SNAPSHOT
          ports:
            - containerPort: 8002
          env:
            - name: spring.profiles.active
              value: prod
            - name: spring.config.location
              value: classpath:/config/common/,classpath:/config/prod/
            - name: spring.cloud.config.server.security.password
              value: \{bcrypt\}$2a$10$brIjl4/GAjWZGvo/lKxUAe8/I7Aqas4NIo8eIVSrNF2Y0UbpCmJd2
            - name: spring.cloud.config.server.security.username
            - name: GIT_HUB_PASSWORD
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: local-config-server
spec:
  selector:
    app: local-config-server
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30002
  type: NodePort