server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          uri:
          username: craigmiller160@gmail.com
          password: ${GIT_HUB_PASSWORD}
          search-paths:
            - '*'