server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/craigmiller160/local-config-server-store.git
          username: craigmiller160@gmail.com
          password: ${GIT_HUB_PASSWORD}
          search-paths:
            - '*'
        security:
          username: config-server-user
          password: '{bcrypt}$2a$10$lz.0VwmpdubNVy4quE57FOk3FYTcB6GGSyKCA9RG0Xaj00ojJ5QXW'