server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/craigmiller160/local-config-server-store.git
          username: craigmiller160@gmail.com
          password: ${GIT_HUB_PASSWORD}
          search-paths:
            - '*'